export const GET_LOGGED_IN = "GET_LOGGED_IN";
export const FETCH_USER = "FETCH_USER"; 
export const FETCH_NOW_PLAYING = "FETCH_NOW_PLAYING";
export const FETCH_RECENTLY_PLAYED = 'FETCH_RECENTLY_PLAYED';
export const SELECT_TRACK = 'SELECT_TRACK';
export const SET_TRACK_LOADING = 'SET_TRACK_LOADING';
export const SET_TRACK_LOADED = 'SET_TRACK_LOADED';
